// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppTournament: typeof import('./src/components/AppTournament.vue')['default']
    ComboButton: typeof import('./src/components/ComboButton.vue')['default']
    copy: typeof import('./src/components/StandingsTable copy.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    HeaderLine: typeof import('./src/components/HeaderLine.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    'Mdi:accountMultiplePlus': typeof import('~icons/mdi/account-multiple-plus')['default']
    'Mdi:checkList': typeof import('~icons/mdi/check-list')['default']
    'Mdi:chevronDown': typeof import('~icons/mdi/chevron-down')['default']
    'Mdi:chevronLeft': typeof import('~icons/mdi/chevron-left')['default']
    'Mdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    'Mdi:chevronUp': typeof import('~icons/mdi/chevron-up')['default']
    'Mdi:karate': typeof import('~icons/mdi/karate')['default']
    'Mdi:list': typeof import('~icons/mdi/list')['default']
    'Mdi:listBoxOutline': typeof import('~icons/mdi/list-box-outline')['default']
    'Mdi:tournament': typeof import('~icons/mdi/tournament')['default']
    MdiClipboardListOutline: typeof import('~icons/mdi/clipboard-list-outline')['default']
    MdiGoogle: typeof import('~icons/mdi/google')['default']
    MdiHockeySticks: typeof import('~icons/mdi/hockey-sticks')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiInfo: typeof import('~icons/mdi/info')['default']
    MdiInformation: typeof import('~icons/mdi/information')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MdiStar: typeof import('~icons/mdi/star')['default']
    MdiStart: typeof import('~icons/mdi/start')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandingsGame: typeof import('./src/components/StandingsGame.vue')['default']
    StandingsTable: typeof import('./src/components/StandingsTable.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
