// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComboButton: typeof import('./src/components/ComboButton.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    HeaderLine: typeof import('./src/components/HeaderLine.vue')['default']
    'Mdi:cardsHeart': typeof import('~icons/mdi/cards-heart')['default']
    'Mdi:cardsHeartOutline': typeof import('~icons/mdi/cards-heart-outline')['default']
    'Mdi:check': typeof import('~icons/mdi/check')['default']
    'Mdi:chevronDown': typeof import('~icons/mdi/chevron-down')['default']
    'Mdi:chevronLeft': typeof import('~icons/mdi/chevron-left')['default']
    'Mdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    'Mdi:chevronUp': typeof import('~icons/mdi/chevron-up')['default']
    'Mdi:cloudDownload': typeof import('~icons/mdi/cloud-download')['default']
    'Mdi:contentSave': typeof import('~icons/mdi/content-save')['default']
    'Mdi:fullscreen': typeof import('~icons/mdi/fullscreen')['default']
    'Mdi:karate': typeof import('~icons/mdi/karate')['default']
    'Mdi:listBoxOutline': typeof import('~icons/mdi/list-box-outline')['default']
    'Mdi:lock': typeof import('~icons/mdi/lock')['default']
    'Mdi:lockOpen': typeof import('~icons/mdi/lock-open')['default']
    'Mdi:outlineDownloading': typeof import('~icons/mdi/outline-downloading')['default']
    'Mdi:progressDownload': typeof import('~icons/mdi/progress-download')['default']
    'Mdi:send': typeof import('~icons/mdi/send')['default']
    'Mdi:star': typeof import('~icons/mdi/star')['default']
    'Mdi:swapVertical': typeof import('~icons/mdi/swap-vertical')['default']
    'Mdi:tournament': typeof import('~icons/mdi/tournament')['default']
    MdiClipboardListOutline: typeof import('~icons/mdi/clipboard-list-outline')['default']
    MdiGoogle: typeof import('~icons/mdi/google')['default']
    MdiHockeySticks: typeof import('~icons/mdi/hockey-sticks')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiInformation: typeof import('~icons/mdi/information')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MdiStar: typeof import('~icons/mdi/star')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandingsTable: typeof import('./src/components/StandingsTable.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
